# Generated by Django 5.2.5 on 2025-09-05 18:58

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_certificate_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=core.fields.MyCloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificates/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=core.fields.MyCloudinaryField(blank=True, max_length=255, null=True, verbose_name='portfolio_images/'),
        ),
    ]
